// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnxepqwoctaosvhoelxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJueGVwcXdvY3Rhb3N2aG9lbHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODQ3MzMsImV4cCI6MjA1OTg2MDczM30.hCPtSd28soKKSthFbBvrzi-k7CdpOTgSswMJ0cxwA5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);